version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3316:3306'
    environment:
       MYSQL_DATABASE: 'my-doc-db'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db








# version: '3'

# services:
#   db:
#     image: mysql:latest
#     ports:
#      - '3316:3306'
#     environment:
#      - "MYSQL_DATABASE= 'my-doc-db'"
#      - "MYSQL_ROOT_PASSWORD= 'password'"
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#      - "8000:8000"
#     depends_on:
#      - db